version: '3.8'

services:
  back:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/src
    ports:
      - 8000:8000
    
  front:
    build: ./front
    command: npm run start
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    depends_on:
      - back
